#!/bin/sh

case=${PWD##*/}
drive=$1

# Compact and split
tar -zcvf - $case  | split --bytes=20GB --suffix-length=3 --numeric-suffixes=1 - $case.tgz.

# Upload
rclone copy -vv . --include "$case.tgz.*" $drive:Temp/

# Try this if above does not work

#for loop in $(ls *.tgz)
#	do
#		rclone copy $loop $drive:Temp/
#	done
