#!/bin/sh

# This script compacts files and uploads using rclone

usage()
{ 
	echo -e "Usage:\n"\
	"tarUpload [OPTIONS] [FOLDER NAME]\n"\
	"Options:\n"\
	"[-p [# of Processes] Compacts in parallel mode]\n"\
	"[-h Returns the usage of this script]\n"\
	"[-u Uploads the compacted cases to the cloud]\n"\
	"[--all Uploads all .tgz files to the cloud]" 1>&2; exit 1;
}

# Read the arguments
while getopts :hu-allp: opt; do
	case ${opt} in
		p)
			par=1
			re='^[0-9]+$'
			if [[ ${OPTARG} =~ $re ]]; then #if integer variable exists
				processes=${OPTARG}
			fi;;
		u)
			upload=1;;
		-all)
			all=1;;
		h | *)
			usage;;
	esac
done
# Take Folder Name
shift $(($OPTIND-1))
FOLDER=$1

if [[ -z "${FOLDER}" && -z "${all}" ]]; then
	usage
fi

if [[ -z "${par}" ]]; then
	tar -zcvf ${FOLDER}.tgz ${FOLDER} > tarUpload${FOLDER}.log
	echo "Folder Compacted"
elif [[ -n ${processes} ]]; then
	tar cfv - ${FOLDER} | pigz -9 -p ${processes} > ${FOLDER}.tgz
	echo "Folder Compacted with ${processes} processes."
else
	usage
fi

if [[ ${upload} -eq 1 ]]; then
	rclone copy -vv ${FOLDER}.tgz LUIZ:tempResults/ 1>& tarUpload${FOLDER}Rclone.log
	echo "Folder Uploaded"
elif [[ ${all} -eq 1 ]]; then
	rclone copy -vv . --include "*.tgz" LUIZ:tempResults/ 1>& tarUploadALLRclone.log
	echo "All folders Uploaded"
fi

echo -e "All Done"
