#!/bin/bash

## Options
################### Add User
if [[ $1 == "-u" ]]; then
	echo -e "\n$2 $3" >> $HOME/telebot/users
	echo -e "The user $2 was successfully added"
	exit 0
fi

################### Add bot
if [[ $1 == "-b" ]]; then
	echo -e "$2" > $HOME/telebot/token
	echo -e "The token $2 was successfully added"
	exit 0
fi

## INIT__
TOKEN=$(<$HOME/telebot/token) || clear
USERS=$(<$HOME/telebot/users) || clear

################### token or files not found
if [ -z "$TOKEN" ]; then
	echo -e "No bot TOKEN specified.\nPlease add bot API key to the token file by:\n"
	echo -e "telebot -b [API key]\n"
	exit 1
fi
if [ -z "$USERS" ]; then
	echo -e "No user values found.\n\nYou can add this user by using:\n"
	echo -e "telebot -u [user] [userID]\n"
	exit 1
fi

################### Send
if [[ $1 == "-s" ]]; then
	if [ $2 == "$(cat $HOME/telebot/users | grep $2 | awk '{print $1}')" ]; then
		CHATID="$(cat $HOME/telebot/users | grep $2 | awk '{print $2}')"
	else
		clear
		echo -e "Sorry, user \"$2\" was not found.\nYou can add this user by using:\n"
		echo -e "telebot -u [user] [userID]\n"
		exit 1
	fi
	if [ ${#CHATID} != 9 ]; then
		echo "Sorry, user \"$2\" CHATID has a unusual lenght and is most likely incorrect."
		exit 1
	fi
	MESSAGE=${3:-$(</dev/stdin)} #takes message input from $3, in case it is not set (null value), takes message from standard input (eg.: an echo piped)
	curl -s -X POST https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHATID -d text="$MESSAGE" -d parse_mode="markdown" > /dev/null
	echo -e "Sent to $2: $MESSAGE"
	exit 2
fi
