#!/bin/bash
TOKEN=$(<token)
STDIN=$(cat)

MESSAGE=$STDIN
################### Add user
if [[ -z "$TOKEN" ]]; then
	echo "No TOKEN values found.\nPlease add users by sending:\ntelebot -a [user] [token]"
fi
if [[ $1 == "-a" ]] then
	echo "$2\t$3">>$HOME/telebot/token
fi
# diego=773945556
# luiz=704337050
################### Send
if [[ $1 == "-s" ]]; then
	if [ $2 == "$(grep TOKEN | cut -d "\t" -f1)" ]
		then CHATID="$(grep TOKEN | cut -d "\t" -f2)"
	else
		echo "Sorry, user was not found."
	exit 1
	fi

	curl -s -X POST https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHATID -d text="$MESSAGE" -d parse_mode="markdown" > /dev/null
	echo -e "Sent to $1: $MESSAGE"
fi
